backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Články"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titulok", name: "title", widget: "string" }
      - { label: "Dátum", name: "date", widget: "datetime" }
      - { label: "Telo článku", name: "body", widget: "markdown" }
