backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Články"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Názov", name: "title", widget: "string", required: true }
      - { label: "Dátum", name: "date", widget: "datetime" }
      - { label: "Obrázok", name: "thumbnail", widget: "image" }
      - { label: "Obsah", name: "body", widget: "markdown" }
